
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Python\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1600x900")
window.configure(bg = "#212121")


canvas = Canvas(
    window,
    bg = "#212121",
    height = 900,
    width = 1600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    530.0,
    582.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    333.0,
    744.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    530.0,
    744.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    333.0,
    582.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    530.0,
    420.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    333.0,
    420.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    738.0,
    294.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    935.0,
    582.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    935.0,
    386.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    776.0,
    471.0,
    image=image_image_10
)

canvas.create_text(
    451.0,
    279.0,
    anchor="nw",
    text="Team Name",
    fill="#FFFFFF",
    font=("Roboto Bold", 36 * -1)
)

canvas.create_text(
    812.0,
    367.0,
    anchor="nw",
    text="Overall statistics",
    fill="#FFFFFF",
    font=("Roboto Bold", 32 * -1)
)

canvas.create_text(
    1023.0,
    270.0,
    anchor="nw",
    text="12",
    fill="#FFFFFF",
    font=("Roboto Bold", 40 * -1)
)

canvas.create_text(
    283.0,
    462.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    283.0,
    624.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    283.0,
    786.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    480.0,
    624.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    480.0,
    786.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    327.0,
    462.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    327.0,
    624.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    327.0,
    786.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    524.0,
    624.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    524.0,
    786.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    377.0,
    463.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

canvas.create_text(
    377.0,
    625.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

canvas.create_text(
    377.0,
    787.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

canvas.create_text(
    574.0,
    625.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

canvas.create_text(
    574.0,
    787.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

canvas.create_text(
    1158.0,
    271.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 40 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    281.0,
    294.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    960.0,
    664.0,
    image=image_image_12
)

canvas.create_text(
    689.0,
    446.0,
    anchor="nw",
    text="Pistol round win rate",
    fill="#FFFFFF",
    font=("Roboto Bold", 12 * -1)
)

canvas.create_text(
    669.0,
    462.0,
    anchor="nw",
    text="68%",
    fill="#FFFFFF",
    font=("Roboto Bold", 24 * -1)
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    776.0,
    553.0,
    image=image_image_13
)

canvas.create_text(
    675.0,
    527.0,
    anchor="nw",
    text="Longest win streak",
    fill="#FFFFFF",
    font=("Roboto Bold", 12 * -1)
)

canvas.create_text(
    673.0,
    546.0,
    anchor="nw",
    text="6 matches",
    fill="#FFFFFF",
    font=("Roboto Bold", 24 * -1)
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    864.0,
    634.0,
    image=image_image_14
)

canvas.create_text(
    675.0,
    607.0,
    anchor="nw",
    text="Closest Win",
    fill="#FFFFFF",
    font=("Roboto Bold", 12 * -1)
)

canvas.create_text(
    671.0,
    626.0,
    anchor="nw",
    text="19 - 17 VS Made in Poland",
    fill="#FFFFFF",
    font=("Roboto Bold", 24 * -1)
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    864.0,
    714.0,
    image=image_image_15
)

canvas.create_text(
    673.0,
    688.0,
    anchor="nw",
    text="Closest loss",
    fill="#FFFFFF",
    font=("Roboto Bold", 12 * -1)
)

canvas.create_text(
    671.0,
    707.0,
    anchor="nw",
    text="11 - 13 VS Kreatures",
    fill="#FFFFFF",
    font=("Roboto Bold", 24 * -1)
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    267.0,
    472.0,
    image=image_image_16
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    267.0,
    634.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    267.0,
    796.0,
    image=image_image_18
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    464.0,
    634.0,
    image=image_image_19
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    464.0,
    796.0,
    image=image_image_20
)

image_image_21 = PhotoImage(
    file=relative_to_assets("image_21.png"))
image_21 = canvas.create_image(
    357.0,
    472.0,
    image=image_image_21
)

image_image_22 = PhotoImage(
    file=relative_to_assets("image_22.png"))
image_22 = canvas.create_image(
    357.0,
    634.0,
    image=image_image_22
)

image_image_23 = PhotoImage(
    file=relative_to_assets("image_23.png"))
image_23 = canvas.create_image(
    357.0,
    796.0,
    image=image_image_23
)

image_image_24 = PhotoImage(
    file=relative_to_assets("image_24.png"))
image_24 = canvas.create_image(
    554.0,
    634.0,
    image=image_image_24
)

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    554.0,
    796.0,
    image=image_image_25
)

image_image_26 = PhotoImage(
    file=relative_to_assets("image_26.png"))
image_26 = canvas.create_image(
    1119.0,
    295.0,
    image=image_image_26
)

image_image_27 = PhotoImage(
    file=relative_to_assets("image_27.png"))
image_27 = canvas.create_image(
    991.0,
    294.0,
    image=image_image_27
)

image_image_28 = PhotoImage(
    file=relative_to_assets("image_28.png"))
image_28 = canvas.create_image(
    677.0,
    452.0,
    image=image_image_28
)

image_image_29 = PhotoImage(
    file=relative_to_assets("image_29.png"))
image_29 = canvas.create_image(
    309.0,
    472.0,
    image=image_image_29
)

image_image_30 = PhotoImage(
    file=relative_to_assets("image_30.png"))
image_30 = canvas.create_image(
    309.0,
    634.0,
    image=image_image_30
)

image_image_31 = PhotoImage(
    file=relative_to_assets("image_31.png"))
image_31 = canvas.create_image(
    309.0,
    796.0,
    image=image_image_31
)

image_image_32 = PhotoImage(
    file=relative_to_assets("image_32.png"))
image_32 = canvas.create_image(
    506.0,
    634.0,
    image=image_image_32
)

image_image_33 = PhotoImage(
    file=relative_to_assets("image_33.png"))
image_33 = canvas.create_image(
    506.0,
    796.0,
    image=image_image_33
)

canvas.create_text(
    480.0,
    462.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    524.0,
    462.0,
    anchor="nw",
    text="4",
    fill="#FFFFFF",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    574.0,
    463.0,
    anchor="nw",
    text="40 %",
    fill="#FFFFFF",
    font=("Roboto Bold", 15 * -1)
)

image_image_34 = PhotoImage(
    file=relative_to_assets("image_34.png"))
image_34 = canvas.create_image(
    464.0,
    472.0,
    image=image_image_34
)

image_image_35 = PhotoImage(
    file=relative_to_assets("image_35.png"))
image_35 = canvas.create_image(
    554.0,
    472.0,
    image=image_image_35
)

image_image_36 = PhotoImage(
    file=relative_to_assets("image_36.png"))
image_36 = canvas.create_image(
    506.0,
    472.0,
    image=image_image_36
)
window.resizable(False, False)
window.mainloop()
